<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExampleProject.Repository\ExampleProject.Repository.csproj" />
    <ProjectReference Include="..\ExampleProjest.Service.Common\ExampleProject.Service.Common.csproj" />
  </ItemGroup>

</Project>
