create table "Store" (
	"Id" INTEGER generated by default as identity primary key not null,
	"Address" VARCHAR(255) not null
);

create table "ClothingItem" (
	"Id" INTEGER generated by default as identity primary key not null,
	"Name" VARCHAR(255) not null,
	"Type" VARCHAR(255) not null,
	"Sizes" VARCHAR(255) not null,
	"Material" VARCHAR(255),
	"Description" TEXT
);

create table "Customer" (
	"Id" INTEGER generated by default as identity primary key not null,
	"FirstName"  VARCHAR(255) not null,
	"LastName"  VARCHAR(255) not null
);

create table "Employee" (
	"Id" INTEGER generated by default as identity primary key not null,
	"FirstName"  VARCHAR(255) not null,
	"LastName"  VARCHAR(255) not null,
	"StoreId" INTEGER references "Store"("Id") not null,
	"StartedOn" DATE not null
);

create table "Order" (
	"Id" INTEGER generated by default as identity primary key not null,
	"EmployeeId" INTEGER references "Employee"("Id") not null,
	"CustomerId" INTEGER references "Customer"("Id") not null,
	"StoreId" INTEGER references "Store"("Id") not null,
	"CreatedAt" timestamp default current_timestamp not null
);

create table "OrderItem" (
	"Id" INTEGER generated by default as identity primary key not null,
	"OrderId" INTEGER references "Order"("Id") not null,
	"ClothingItemId" INTEGER references "ClothingItem"("Id") not null
);

INSERT INTO "Store" ("Id", "Address") VALUES(DEFAULT, 'Osijek, Ulica Kralja Tomislava 11');
INSERT INTO "Store" ("Id", "Address") VALUES(DEFAULT, 'Zagreb, Ulica Kralja Tomislava 108');
INSERT INTO "Store" ("Id", "Address") VALUES(DEFAULT, 'Osijek, Ulica J.J. Strossmayera 12');

INSERT INTO "ClothingItem" ("Id", "Name", "Type", "Sizes", "Material", "Description") VALUES(DEFAULT, 'Dugacke hlace', 'Hlace', 'S, L, XL', 'Denim', 'Dugacke hlace od denima');
INSERT INTO "ClothingItem" ("Id", "Name", "Type", "Sizes", "Material", "Description") VALUES(DEFAULT, 'Dugacke hlace', 'Hlace', 'S, M, L', 'Linen', 'Dugacke linene hlace');
INSERT INTO "ClothingItem" ("Id", "Name", "Type", "Sizes", "Material", "Description") VALUES(DEFAULT, 'Kratke hlace', 'Hlace', 'L', 'Pamuk', 'Kratke pamucne hlace');

INSERT INTO "Customer" ("Id", "FirstName", "LastName") VALUES(DEFAULT, 'Pero', 'Peric');
INSERT INTO "Customer" ("Id", "FirstName", "LastName") VALUES(DEFAULT, 'Marko', 'Markic');
INSERT INTO "Customer" ("Id", "FirstName", "LastName") VALUES(DEFAULT, 'Ana', 'Anic');

INSERT INTO "Employee" ("Id", "FirstName", "LastName", "StoreId", "StartedOn") VALUES(DEFAULT, 'Jana', 'Janic', 1, '19.1.2026');
INSERT INTO "Employee" ("Id", "FirstName", "LastName", "StoreId", "StartedOn") VALUES(DEFAULT, 'Petar', 'Perkovic', 2, '13.3.2021');
INSERT INTO "Employee" ("Id", "FirstName", "LastName", "StoreId", "StartedOn") VALUES(DEFAULT, 'Luka', 'Lukic', 3, '27.3.2024');

INSERT INTO "Order" ("Id", "EmployeeId", "CustomerId", "StoreId", "CreatedAt") VALUES(DEFAULT, 1, 2, 3, DEFAULT);
INSERT INTO "Order" ("Id", "EmployeeId", "CustomerId", "StoreId", "CreatedAt") VALUES(DEFAULT, 2, 1, 3, DEFAULT);
INSERT INTO "Order" ("Id", "EmployeeId", "CustomerId", "StoreId", "CreatedAt") VALUES(DEFAULT, 4, 2, 1, DEFAULT);

INSERT INTO "OrderItem" ("Id", "OrderId", "ClothingItemId") VALUES(DEFAULT, 1, 1);
INSERT INTO "OrderItem" ("Id", "OrderId", "ClothingItemId") VALUES(DEFAULT, 2, 1);
INSERT INTO "OrderItem" ("Id", "OrderId", "ClothingItemId") VALUES(DEFAULT, 3, 2);

select o."Id", e."FirstName" as "Employee name", e."LastName" as "Employee surname",
c."FirstName" as "Customer name", c."LastName" as "Customer surname",
ci."Name" as "Product name", ci."Material", ci."Description" as "Product description",
o."CreatedAt"
	from "Order" as o
		left join "Employee" as e on (o."EmployeeId" = e."Id")
		left join "OrderItem" as i on (o."Id" = i."OrderId")
		join "ClothingItem" as ci on (i."ClothingItemId" = ci."Id")
		left join "Customer" as c on (c."Id" = o."CustomerId" )
		order by o."CreatedAt" ASC;

select * from "ClothingItem" as ci
	left join "OrderItem" as i on (i."ClothingItemId" = ci."Id")
	right join "Order" as o on (i."OrderId" = o."Id");

delete from select * from "ClothingItem" as ci
	left join "OrderItem" as i on (i."ClothingItemId" = ci."Id")
	right join "Order" as o on (i."OrderId" = o."Id")
		where("ClothingItemId" == null);

delete from select * from "Order"
	where ("CreatedAt" between ('1.1.2025' and '31.1.2026'));

update "ClothingItem" set "Description" = 'Dugacke plave linene hlace'
	where (ci."Material" = 'linen');
update "Order" set "CreatedAt" = current_timestamp
	where("CreatedAt" between ('1.1.2023' and '1.2.2023'));