create table "Category" (
	"Id" INTEGER generated by default as identity primary key not null,
	"Name" VARCHAR(255) not null
);

create table "Product" (
	"Id" INTEGER generated by default as identity primary key not null,
	"Name" VARCHAR(255) not null,
	"Stock" INTEGER,
	"Description" TEXT,
	"CategoryId" INTEGER references "Category"("Id")
);

insert into "Category" values(default, 'Odjeca');
insert into "Category" values(default, 'Hrana');
insert into "Category" values(default, 'Alati');
insert into "Product" values(default, 'Banana', 125, '', 1);
insert into "Product" values(default, 'Krastavac', 243, '', 2);
insert into "Product" values(default, 'Hlace', 13, '', 1);

update "Product" set ("Stock" = "Stock" - 1) where ("Id" = 2);
update "Product" set ("CategoryId" = 2) where ("Id" = 1);

delete from "Product" where("Stock" < 15);
delete from "Category" where("Id" = 3);

select p."Name", p."Description", c."Name" as "Category", p."Stock" from "Product" as p
	left join "Category" as c on (p."CategoryId" = c."Id")
	where(p."CategoryId" = c."Id");

select "Name" from "Category";
 